"""
RentFux — MongoDB JSON  →  MySQL INSERT generator
====================================================
Reads the JSON exports next to this script and writes a single
`data.sql` file with INSERT statements that match `schema_mysql.sql`.

Usage:
    cd /app/export
    pip install python-dateutil
    python3 migrate_to_mysql.py

Then in MySQL:
    mysql -u root -p rentfux < schema_mysql.sql
    mysql -u root -p rentfux < data.sql

Notes:
- Nested fields in Mongo (e.g. users.profile, users.company) are flattened.
- Document uploads and feature/image arrays are extracted to side tables.
- Datetime strings (ISO 8601) are converted to MySQL DATETIME(6).
- Anything missing in source is inserted as NULL.
"""
from __future__ import annotations
import json
import os
import sys
from datetime import datetime, date
from typing import Any, Optional

HERE = os.path.dirname(os.path.abspath(__file__))
OUT  = os.path.join(HERE, "data.sql")


# ---------------- utilities ----------------
def load(name: str) -> list:
    path = os.path.join(HERE, name)
    if not os.path.exists(path):
        print(f"  (skip) {name} missing")
        return []
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    print(f"  loaded {len(data):5d} from {name}")
    return data


def esc(v: Any) -> str:
    """SQL-escape a Python value for a MySQL VALUES list."""
    if v is None or v == "":
        return "NULL"
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, (datetime, date)):
        return f"'{v.isoformat(sep=' ')}'"
    s = str(v).replace("\\", "\\\\").replace("'", "''")
    return f"'{s}'"


def parse_dt(value: Any) -> Optional[str]:
    if not value:
        return None
    if isinstance(value, dict) and "$date" in value:
        value = value["$date"]
    try:
        dt = datetime.fromisoformat(str(value).replace("Z", "+00:00"))
        return dt.strftime("%Y-%m-%d %H:%M:%S.%f")[:-3]
    except Exception:
        return None


def parse_date(value: Any) -> Optional[str]:
    if not value:
        return None
    try:
        return datetime.fromisoformat(str(value).replace("Z", "+00:00")).strftime("%Y-%m-%d")
    except Exception:
        try:
            return datetime.strptime(str(value)[:10], "%Y-%m-%d").strftime("%Y-%m-%d")
        except Exception:
            return None


def insert(out, table: str, cols: list[str], rows: list[list[Any]]):
    if not rows:
        return
    out.write(f"-- {table}: {len(rows)} rows\n")
    out.write(f"INSERT INTO `{table}` (`" + "`, `".join(cols) + "`) VALUES\n")
    parts = []
    for r in rows:
        parts.append("  (" + ", ".join(esc(x) for x in r) + ")")
    out.write(",\n".join(parts))
    out.write(";\n\n")


# ---------------- main ----------------
def main():
    print("Loading exports...")
    locations    = load("locations.json")
    users        = load("users.json")
    vehicles     = load("vehicles.json")
    discounts    = load("discount_codes.json")
    bookings     = load("bookings.json")
    positions    = load("vehicle_positions.json")
    attempts     = load("login_attempts.json")

    with open(OUT, "w", encoding="utf-8") as out:
        out.write("-- RentFux MySQL data dump\n")
        out.write("-- Generated by migrate_to_mysql.py\n")
        out.write("SET FOREIGN_KEY_CHECKS=0;\n")
        out.write("SET NAMES utf8mb4;\n\n")

        # ---- locations ----
        rows = []
        for l in locations:
            rows.append([
                l.get("id"), l.get("name"), l.get("address"),
                l.get("city"), l.get("postal_code"), l.get("phone"),
                l.get("email"), bool(l.get("active", True)),
                parse_dt(l.get("created_at")) or datetime.utcnow(),
            ])
        insert(out, "locations",
               ["id", "name", "address", "city", "postal_code", "phone",
                "email", "active", "created_at"], rows)

        # ---- users ----
        u_rows, doc_rows = [], []
        for u in users:
            profile = u.get("profile") or {}
            company = u.get("company") or {}
            docs    = (profile.get("documents") or {})
            u_rows.append([
                u.get("id"), u.get("email"), u.get("password_hash"),
                u.get("role", "user"), u.get("name") or u.get("email"),
                u.get("phone"),
                profile.get("address"), profile.get("postal_code"),
                profile.get("city"), profile.get("country", "Deutschland"),
                parse_date(profile.get("date_of_birth")),
                profile.get("license_number"), profile.get("license_country"),
                parse_date(profile.get("license_issued_at")),
                parse_date(profile.get("license_expires_at")),
                bool(u.get("is_business", False)),
                company.get("name"), company.get("vat_id"),
                company.get("contact_name"), company.get("contact_email"),
                bool(u.get("profile_complete", False)),
                parse_dt(u.get("created_at")) or datetime.utcnow(),
                parse_dt(u.get("updated_at")),
            ])
            for doc_type in ("license", "id_card"):
                d = docs.get(doc_type)
                if d and d.get("path"):
                    doc_rows.append([
                        u["id"], doc_type, d.get("path"),
                        d.get("filename"), d.get("content_type"),
                        d.get("size"), parse_dt(d.get("uploaded_at")),
                    ])
        insert(out, "users",
               ["id", "email", "password_hash", "role", "name", "phone",
                "address_street", "address_postal_code", "address_city",
                "address_country", "date_of_birth", "license_number",
                "license_country", "license_issued_at", "license_expires_at",
                "is_business", "company_name", "company_vat_id",
                "company_contact_name", "company_contact_email",
                "profile_complete", "created_at", "updated_at"], u_rows)
        insert(out, "user_documents",
               ["user_id", "doc_type", "storage_path", "filename",
                "content_type", "size_bytes", "uploaded_at"], doc_rows)

        # ---- discount_codes ----
        rows = []
        for d in discounts:
            rows.append([
                d.get("code"), d.get("description"),
                d.get("type") or d.get("discount_type", "percent"),
                d.get("value", 0),
                d.get("min_total"), d.get("max_uses"),
                d.get("used_count", 0),
                parse_dt(d.get("valid_from")), parse_dt(d.get("valid_until")),
                bool(d.get("active", True)),
                parse_dt(d.get("created_at")) or datetime.utcnow(),
            ])
        insert(out, "discount_codes",
               ["code", "description", "discount_type", "value", "min_total",
                "max_uses", "used_count", "valid_from", "valid_until",
                "active", "created_at"], rows)

        # ---- vehicles + images + features ----
        v_rows, img_rows, feat_rows = [], [], []
        for v in vehicles:
            last = v.get("last_position") or {}
            v_rows.append([
                v["id"], v.get("brand"), v.get("name"),
                v.get("category"), v.get("transmission"), v.get("fuel"),
                v.get("seats", 5), v.get("doors", 4),
                v.get("price_per_day", 0), v.get("image_url"),
                v.get("description"), bool(v.get("active", True)),
                v.get("location_id"),
                last.get("lat"), last.get("lng"),
                last.get("speed_kmh"), last.get("heading"),
                last.get("status"), parse_dt(last.get("ts")),
                parse_dt(v.get("created_at")) or datetime.utcnow(),
            ])
            for i, url in enumerate(v.get("images") or []):
                img_rows.append([v["id"], url, i])
            for feat in v.get("features") or []:
                feat_rows.append([v["id"], feat])
        insert(out, "vehicles",
               ["id", "brand", "name", "category", "transmission", "fuel",
                "seats", "doors", "price_per_day", "image_url", "description",
                "active", "location_id", "last_lat", "last_lng",
                "last_speed_kmh", "last_heading", "last_status", "last_ts",
                "created_at"], v_rows)
        insert(out, "vehicle_images",
               ["vehicle_id", "url", "sort_order"], img_rows)
        insert(out, "vehicle_features",
               ["vehicle_id", "feature_name"], feat_rows)

        # ---- bookings + extras ----
        b_rows, e_rows = [], []
        for b in bookings:
            cust = b.get("customer") or {}
            b_rows.append([
                b["id"], b.get("user_id"), b.get("vehicle_id"),
                bool(b.get("is_guest", False)),
                cust.get("name") or b.get("user_name"),
                cust.get("email") or b.get("user_email"),
                cust.get("phone"),
                parse_date(cust.get("date_of_birth")),
                cust.get("license_number"),
                cust.get("address"), cust.get("postal_code"),
                cust.get("city"), cust.get("country"),
                b.get("vehicle_brand"), b.get("vehicle_name"),
                b.get("pickup_location_id") or b.get("location_id"),
                b.get("return_location_id") or b.get("location_id"),
                parse_date(b.get("start_date")), parse_date(b.get("end_date")),
                b.get("pickup_time"), b.get("return_time"),
                int(b.get("days", 1)),
                b.get("base_subtotal", b.get("subtotal", 0)),
                b.get("extras_total", 0),
                b.get("discount_code"), b.get("discount_amount", 0),
                b.get("total", 0),
                b.get("status", "pending"),
                b.get("payment_method"),
                b.get("payment_status", "pending"),
                bool(b.get("vehicle_deleted", False)),
                bool(b.get("user_deleted", False)),
                parse_dt(b.get("cancelled_at")),
                parse_dt(b.get("created_at")) or datetime.utcnow(),
                parse_dt(b.get("updated_at")),
            ])
            for ex in (b.get("extras") or []):
                if isinstance(ex, str):
                    e_rows.append([b["id"], ex, 0])
                elif isinstance(ex, dict):
                    e_rows.append([b["id"], ex.get("name"), ex.get("price", 0)])
        insert(out, "bookings",
               ["id", "user_id", "vehicle_id", "is_guest",
                "customer_name", "customer_email", "customer_phone",
                "customer_dob", "customer_license", "customer_address",
                "customer_postal", "customer_city", "customer_country",
                "vehicle_brand", "vehicle_name",
                "pickup_location_id", "return_location_id",
                "start_date", "end_date", "pickup_time", "return_time",
                "days", "base_subtotal", "extras_total", "discount_code",
                "discount_amount", "total", "status", "payment_method",
                "payment_status", "vehicle_deleted", "user_deleted",
                "cancelled_at", "created_at", "updated_at"], b_rows)
        insert(out, "booking_extras",
               ["booking_id", "extra_name", "extra_price"], e_rows)

        # ---- vehicle_positions ----
        rows = []
        for p in positions:
            rows.append([
                p["id"], p["vehicle_id"],
                p.get("lat", 0), p.get("lng", 0),
                p.get("speed_kmh", 0), p.get("heading", 0),
                p.get("status", "parked"), p.get("source", "mock"),
                p.get("fence_km", 0), bool(p.get("geofence_alert", False)),
                parse_dt(p.get("ts")) or datetime.utcnow(),
                int(p.get("ts_epoch", 0)),
            ])
        insert(out, "vehicle_positions",
               ["id", "vehicle_id", "lat", "lng", "speed_kmh", "heading",
                "status", "source", "fence_km", "geofence_alert",
                "ts", "ts_epoch"], rows)

        # ---- login_attempts ----
        rows = []
        for a in attempts:
            rows.append([
                a.get("identifier"),
                parse_dt(a.get("attempted_at")) or datetime.utcnow(),
                bool(a.get("success", False)),
                a.get("ip"), a.get("user_agent"),
            ])
        insert(out, "login_attempts",
               ["identifier", "attempted_at", "success", "ip", "user_agent"], rows)

        out.write("SET FOREIGN_KEY_CHECKS=1;\n")

    print(f"\nDone -> {OUT}")
    print(f"Size: {os.path.getsize(OUT) / 1024:.1f} KB")


if __name__ == "__main__":
    sys.exit(main() or 0)
